spring:
  jpa:
    show-sql: false
  properties:
    hibernate:
      format_sql: true
  profiles:
    active: development
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: Polkm123!

heb:
  cloud:
    object-detection-provider: Google Vision
    storage-provider: Google Cloud Storage
    supported:
      filetypes:
        IMG: [.jpeg, .png, .gif, .webp, .raw, .ico, .pdf, .tiff]
    # storage-provider: Minio